apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-service
 annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/use-regex: "true"
  nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "1"
  nginx.ingress.kubernetes.io/affinity: "cookie"
  nginx.ingress.kubernetes.io/session-cookie-name: "reactivity_socket"
  nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
 tls:
  - hosts:
    - reactivities
    secretName: reactivities-cert
 rules:
  - host: "reactivities"
    http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: front-cluster-ip-service
          port:
           number: 80
      - path: /api/?(.*)
        pathType: Prefix
        backend:
         service:
          name: api-cluster-ip-service
          port:
           number: 5001
      - path: /chat/?(.*)
        pathType: Prefix
        backend:
         service:
          name: api-cluster-ip-service
          port:
           number: 5001
