apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9093
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: data
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-cluster-ip-service-9092:9092
            - name: KAFKA_CFG_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 1@kafka-cluster-ip-service-9093:9093
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: kafka_local
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_MESSAGE_MAX_BYTES
              value: "30728640"
            - name: KAFKA_CFG_REPLICA_FETCH_MAX_BYTES
              value: "30728640"
      volumes:
        - name: data
          nfs:
            server: 192.168.1.12
            path: "/var/data/Kafka"
---
apiVersion: v1
kind: Service
metadata:
 name: kafka-cluster-ip-service-9092
spec:
 type: ClusterIP
 selector:
  app: kafka
 ports:
  - name: kafka
    protocol: TCP
    port: 9092
    targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
 name: kafka-cluster-ip-service-9093
spec:
 type: ClusterIP
 selector:
  app: kafka
 ports:
  - name: kafka
    protocol: TCP
    port: 9093
    targetPort: 9093
