apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 25672
        - containerPort: 5672
        - containerPort: 4369
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-ip-service
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 15672
    nodePort: 30201
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
 name: rabbitmq-cluster-ip-service
spec:
 type: ClusterIP
 selector:
  app: rabbitmq
 ports:
  - name: rabbitmq
    protocol: TCP
    port: 5672
    targetPort: 5672