apiVersion: apps/v1
kind: Deployment
metadata:
 name: ms-identity-api
spec:
 replicas: 1
 selector:
  matchLabels:
   component: ms-identity-api
 template:
  metadata:
   labels:
    component: ms-identity-api
  spec:
   containers:
    - name: ms-identity-api
      image: kozlovas/ms-identity-api
      ports:
       - containerPort: 5020
      env:
       - name: ASPNETCORE_URLS
         value: "http://+:5020"
       - name: ConnectionStrings__DefaultConnection
         value: "User ID=postgres;Password=admin;Host=postgre-service;Port=5432;Database=MicroServicesIdentity;SearchPath=public"
---
apiVersion: v1
kind: Service
metadata:
 name: ms-identity-api-service
spec:
 type: ClusterIP
 ports:
  - port: 5020
    targetPort: 5020
 selector:
  component: ms-identity-api