apiVersion: apps/v1
kind: Deployment
metadata:
 name: ms-main-api
spec:
 replicas: 1
 selector:
  matchLabels:
   component: ms-main-api
 template:
  metadata:
   labels:
    component: ms-main-api
  spec:
   containers:
    - name: ms-main-api
      image: kozlovas/ms-main-api
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 5022
      env:
       - name: ASPNETCORE_URLS
         value: "http://+:5022"
---
apiVersion: v1
kind: Service
metadata:
 name: ms-main-api-service
spec:
 type: ClusterIP
 ports:
  - port: 5022
    targetPort: 5022
 selector:
  component: ms-main-api