apiVersion: apps/v1
kind: Deployment
metadata:
 name: rb-front
spec:
 replicas: 1
 selector:
  matchLabels:
   component: rb-front
 template:
  metadata:
   labels:
    component: rb-front
  spec:
   containers:
   - name: rb-front
     image: kozlovas/rb-front
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 80
     env:
       - name: NG_APP_API
         value: /api
---
apiVersion: v1
kind: Service
metadata:
 name: rb-front-cluster-ip-service
spec:
 type: ClusterIP
 ports:
  - port: 80
    targetPort: 80
 selector:
  component: rb-front
