apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault-data
  labels:
    name: pv-vault-data
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/home/alex/data/Vault_Data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vault-data
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv-vault-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault-conf
  labels:
    name: pv-vault-conf
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/home/alex/data/Vault_Conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vault-conf
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv-vault-conf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  selector:
    matchLabels:
      app: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.19
          imagePullPolicy: IfNotPresent
          command: ["vault", "server","-config", "/vault/config/config.hcl" ]
          env:
            - name: VAULT_ADDR
              value: http://localhost:8200
          ports:
            - containerPort: 8200
            - containerPort: 8201
          volumeMounts:
            - mountPath: /vault/data
              name: data
            - mountPath: /vault/config
              name: conf
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-vault-data
      - name: conf
        persistentVolumeClaim:
          claimName: pvc-vault-conf
---
apiVersion: v1
kind: Service
metadata:
  name: vault-ip-service
spec:
  selector:
    app: vault
  ports:
  - protocol: TCP
    port: 8200
    nodePort: 30440
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
 name: vault-cluster-ip-service
spec:
 type: ClusterIP
 selector:
  app: vault
 ports:
  - name: vault
    protocol: TCP
    port: 8200
    targetPort: 8200
