apiVersion: apps/v1
kind: Deployment
metadata:
 name: ms-rabbit-consumer
spec:
 replicas: 1
 selector:
  matchLabels:
   component: ms-rabbit-consumer
 template:
  metadata:
   labels:
    component: ms-rabbit-consumer
  spec:
   containers:
    - name: ms-rabbit-consumer
      image: kozlovas/ms-rabbitconsumer
      imagePullPolicy: IfNotPresent
      env:
       - name: ConnectionStrings__DefaultConnection
         value: "User ID=postgres;Password=admin;Host=postgre-service;Port=5432;Database=MicroServices;SearchPath=public"