apiVersion: apps/v1
kind: Deployment
metadata:
 name: rm-front
spec:
 replicas: 1
 selector:
  matchLabels:
   component: front
 template:
  metadata:
   labels:
    component: front
  spec:
   containers:
    - name: front
      image: kozlovas/redmango-front
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 80
      env:
       - name: REACT_APP_API_URL
         value: "/api"
---
apiVersion: v1
kind: Service
metadata:
 name: rm-front-cluster-ip-service
spec:
 type: ClusterIP
 ports:
  - port: 80
    targetPort: 80
 selector:
  component: front
