apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-data
  labels:
    name: pv-prometheus-data
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/files/data/Prometheus_Data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-data
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: pv-prometheus-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-conf
  labels:
    name: pv-prometheus-conf
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/files/data/Prometheus_Conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-conf
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: pv-prometheus-conf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v3.6.0
        args:
          - '--storage.tsdb.retention.time=14d'
          - '--config.file=/etc/prometheus/prometheus.yml'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        volumeMounts:
          - mountPath: /etc/prometheus
            name: prom-conf
          - mountPath: /prometheus
            name: prom-data
      volumes:
      - name: prom-conf
        persistentVolumeClaim:
          claimName: pvc-prometheus-conf
      - name: prom-data
        persistentVolumeClaim:
          claimName: pvc-prometheus-data
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-ip-service
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    nodePort: 30438
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
 name: prometheus-cluster-ip-service
spec:
 type: ClusterIP
 selector:
  app: prometheus
 ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
