apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:8.2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
 name: redis-cluster-ip-service
spec:
 type: ClusterIP
 selector:
  app: redis
 ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-ip-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 8001
    targetPort: 8001

