apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-otc
  labels:
    name: pv-otc
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/files/data/OTC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-otc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: pv-otc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otc
spec:
  selector:
    matchLabels:
      app: otc
  replicas: 1
  template:
    metadata:
      labels:
        app: otc
    spec:
      containers:
      - name: otc
        image: otel/opentelemetry-collector-contrib:0.129.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 4317
        - containerPort: 55679
        - containerPort: 13133
        volumeMounts:
          - mountPath: /etc/otelcol-contrib
            name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-otc
---
apiVersion: v1
kind: Service
metadata:
  name: otc-ip-service-otc
spec:
 type: ClusterIP
 selector:
  app: otc
 ports:
  - name: otc
    protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: otc-ip-service-dotnet
spec:
 type: ClusterIP
 selector:
  app: otc
 ports:
  - name: otc
    protocol: TCP
    port: 8889
    targetPort: 8889
---
apiVersion: v1
kind: Service
metadata:
  name: otc-ip-service-import
spec:
 type: ClusterIP
 selector:
  app: otc
 ports:
  - name: otc
    protocol: TCP
    port: 4317
    targetPort: 4317
---
apiVersion: v1
kind: Service
metadata:
 name: otc-service-dotnet-local
 labels:
   app: otc-service-dotnet-local
spec:
 selector:
   app: otc
 ports:
 - protocol: TCP
   port: 8889
   nodePort: 30437
 type: NodePort
---
apiVersion: v1
kind: Service
metadata:
 name: otc-service-dotnet-local2
 labels:
   app: otc-service-dotnet-local2
spec:
 selector:
   app: otc
 ports:
 - protocol: TCP
   port: 8888
   nodePort: 30436
 type: NodePort
