apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-api-reports
spec:
  selector:
    matchLabels:
      app: auction-api-reports
  template:
    metadata:
      labels:
        app: auction-api-reports
    spec:
      containers:
      - name: auction-api-reports
        image: kozlovas/auction-api-reports
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - cat
            - /app/appsettings.json
          initialDelaySeconds: 60
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: auction-api-reports-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-api-reports
  ports:
  - port: 80
    targetPort: 80

