apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-bid
spec:
  selector:
    matchLabels:
      app: auction-bid
  template:
    metadata:
      labels:
        app: auction-bid
    spec:
      containers:
      - name: auction-bid
        image: kozlovas/auction-bidding
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:80"
          - name: RabbitMq__Host
            value: rabbitmq-cluster-ip-service
---
apiVersion: v1
kind: Service
metadata:
  name: auction-bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-bid
  ports:
  - port: 80
    targetPort: 80
