apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-bid
spec:
  selector:
    matchLabels:
      app: auction-bid
  template:
    metadata:
      labels:
        app: auction-bid
    spec:
      containers:
      - name: auction-bid
        image: kozlovas/auction-bidding
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - cat
            - /app/appsettings.json
          initialDelaySeconds: 60
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auction-bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-bid
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-bid-clusterip-grpc
spec:
  type: ClusterIP
  selector:
    app: auction-bid
  ports:
  - port: 7780
    targetPort: 7780
    name: grpc
