apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-bid
spec:
  selector:
    matchLabels:
      app: auction-bid
  template:
    metadata:
      labels:
        app: auction-bid
    spec:
      containers:
      - name: auction-bid
        image: kozlovas/auction-bidding-api
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:80"
          - name: RabbitMq__Host
            value: rabbitmq-cluster-ip-service
          - name: RabbitMq__Username
            value: guest
          - name: RabbitMq__Password
            value: guest
          - name: ConnectionStrings__DefaultConnection
            value: "User ID=postgres;Password=admin;Host=postgre-service;Port=5432;Database=AuctionsBids;SearchPath=public"
---
apiVersion: v1
kind: Service
metadata:
  name: auction-bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-bid
  ports:
  - port: 80
    targetPort: 80
