apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-elk
  template:
    metadata:
      labels:
        app: auction-elk
    spec:
      containers:
      - name: auction-elk
        image: kozlovas/auction-elk-api
        imagePullPolicy: IfNotPresent
        env:
          - name: RabbitMq__Host
            value: rabbitmq-cluster-ip-service
          - name: RabbitMq__Username
            value: guest
          - name: RabbitMq__Password
            value: guest
          - name: ConnectionStrings__DefaultConnection
            value: "User ID=postgres;Password=admin;Host=postgre-service;Port=5432;Database=AuctionsSearch;SearchPath=public"
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: Http1
          - name: Kestrel__Endpoints__WebApi__Url
            value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-elk-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-elk
  ports:
  - port: 80
    targetPort: 80
