apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-eventsourcing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-eventsourcing
  template:
    metadata:
      labels:
        app: auction-eventsourcing
    spec:
      containers:
      - name: auction-eventsourcing
        image: kozlovas/auction-eventsourcing
        imagePullPolicy: IfNotPresent
        env:
          - name: RabbitMq__Host
            value: rabbitmq-cluster-ip-service
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: Http1
          - name: Kestrel__Endpoints__WebApi__Url
            value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-eventsourcing-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-eventsourcing
  ports:
  - port: 80
    targetPort: 80
    name: web
