apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-gateway
spec:
  selector:
    matchLabels:
      app: auction-gateway
  template:
    metadata:
      labels:
        app: auction-gateway
    spec:
      containers:
      - name: auction-gateway
        image: kozlovas/auction-gateway
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /checkvault
            port: 80
            scheme: HTTP
            host: 10.108.29.192
          failureThreshold: 60
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: auction-gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-gateway
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-gateway-clusterip-grpc
spec:
  type: ClusterIP
  selector:
    app: auction-gateway
  ports:
  - port: 7782
    targetPort: 7782
