apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-gateway
spec:
  selector:
    matchLabels:
      app: auction-gateway
  template:
    metadata:
      labels:
        app: auction-gateway
    spec:
      containers:
      - name: auction-gateway
        image: kozlovas/auction-gateway-api
        imagePullPolicy: IfNotPresent
        env:
          - name: ClientApp
            value: https://auction
          - name: ASPNETCORE_URLS
            value: "http://+:80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-gateway
  ports:
  - port: 80
    targetPort: 80

