apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-identity
  template:
    metadata:
      labels:
        app: auction-identity
    spec:
      containers:
      - name: auction-identity
        image: kozlovas/auction-identity-api
        imagePullPolicy: IfNotPresent
        env:
          - name: ConnectionStrings__DefaultConnection
            value: "User ID=postgres;Password=admin;Host=postgre-service;Port=5432;Database=AuctionsIdentity;SearchPath=public"
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: Http1
          - name: Kestrel__Endpoints__WebApi__Url
            value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-identity
  ports:
  - port: 80
    targetPort: 80
    name: web
