apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-identity
  template:
    metadata:
      labels:
        app: auction-identity
    spec:
      containers:
      - name: auction-identity
        image: kozlovas/auction-identity
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /checkvault
            port: 80
            scheme: HTTP
            host: 10.108.29.192
          failureThreshold: 60
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: auction-identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-identity
  ports:
  - port: 80
    targetPort: 80
    name: web
