apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-image
spec:
  selector:
    matchLabels:
      app: auction-image
  template:
    metadata:
      labels:
        app: auction-image
    spec:
      containers:
      - name: auction-image
        image: kozlovas/auction-image
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - cat
            - /app/appsettings.json
          initialDelaySeconds: 60
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: auction-image-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-image
  ports:
  - port: 7778
    targetPort: 7778
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: auction-image-clusterip-http
spec:
  type: ClusterIP
  selector:
    app: auction-image
  ports:
  - port: 80
    targetPort: 80
