apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-image
spec:
  selector:
    matchLabels:
      app: auction-image
  template:
    metadata:
      labels:
        app: auction-image
    spec:
      containers:
      - name: auction-image
        image: kozlovas/auction-image
        imagePullPolicy: IfNotPresent
        env:
          - name: Kestrel__Endpoints__Grpc__Protocols
            value: Http2
          - name: Kestrel__Endpoints__Grpc__Url
            value: http://+:7778
          - name: RabbitMq__Host
            value: rabbitmq-cluster-ip-service
---
apiVersion: v1
kind: Service
metadata:
  name: auction-image-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-image
  ports:
  - port: 7778
    targetPort: 7778
    name: grpc

