apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-logging
  template:
    metadata:
      labels:
        app: auction-logging
    spec:
      containers:
      - name: auction-logging
        image: kozlovas/auction-logging
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - cat
            - /app/appsettings.json
          initialDelaySeconds: 60
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auction-logging-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-logging
  ports:
  - port: 80
    targetPort: 80
