apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-notify
spec:
  selector:
    matchLabels:
      app: auction-notify
  template:
    metadata:
      labels:
        app: auction-notify
    spec:
      containers:
      - name: auction-notify
        image: kozlovas/auction-notification
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:80"
          - name: RabbitMq__Host
            value: rabbitmq-cluster-ip-service
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-notify-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-notify
  ports:
  - port: 80
    targetPort: 80
