apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-processing
spec:
  selector:
    matchLabels:
      app: auction-processing
  template:
    metadata:
      labels:
        app: auction-processing
    spec:
      containers:
      - name: auction-processing
        image: kozlovas/auction-processing
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - cat
            - /app/appsettings.json
          initialDelaySeconds: 60
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auction-processing-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-processing
  ports:
  - port: 80
    targetPort: 80
