apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: elastic
 labels:
  app: elastic
spec:
 replicas: 1
 selector:
  matchLabels:
   app: elastic
 template:
   metadata:
    labels:
     app: elastic
   spec:
    containers:
    - name: elastic
      image: elasticsearch:8.18.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 9200
        name: elastic
      volumeMounts:
      - mountPath: /usr/share/elasticsearch/data
        name: mydata
      - mountPath: /usr/share/elasticsearch/config
        name: myconf
      resources:
         limits:
           memory: 4Gi
      env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: elastic
    volumes:
    - name: mydata
      nfs:
        server: 192.168.1.12
        path: "/home/alex/data/ELK_Data"
    - name: myconf
      nfs:
        server: 192.168.1.12
        path: "/home/alex/data/ELK_Conf"
---
apiVersion: v1
kind: Service
metadata:
 name: elastic-service
 labels:
   app: elastic-service
spec:
  type: ClusterIP
  selector:
    app: elastic
  ports:
  - name: elastic
    protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
 name: elastic-service-local
 labels:
   app: elastic-service-local
spec:
 selector:
   app: elastic
 ports:
 - protocol: TCP
   port: 9200
   nodePort: 30434
 type: NodePort
