apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kibana-data
  labels:
    name: pv-kibana-data
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/home/alex/data/Kibana_Data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kibana-conf
  labels:
    name: pv-kibana-conf
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/home/alex/data/Kibana_Conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kibana-data
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv-kibana-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kibana-conf
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv-kibana-conf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: kibana
 labels:
  app: kibana
spec:
 replicas: 1
 selector:
  matchLabels:
   app: kibana
 template:
   metadata:
    labels:
     app: kibana
   spec:
    containers:
    - name: kibana
      image: kibana:8.17.3
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 5601
        name: kibana
      env:
        - name: ELASTIC_CONTAINER
          value: "true"
      volumeMounts:
      - mountPath: /usr/share/kibana/config
        name: conf
      - mountPath: /usr/share/kibana/data
        name: data
    volumes:
    - name: conf
      persistentVolumeClaim:
        claimName: pvc-kibana-conf
    - name: data
      persistentVolumeClaim:
        claimName: pvc-kibana-data
---
apiVersion: v1
kind: Service
metadata:
 name: kibana-service-local
 labels:
   app: kibana-service-local
spec:
 selector:
  app: kibana
 type: NodePort
 ports:
  - port: 5601
    nodePort: 30435
---
apiVersion: v1
kind: Service
metadata:
 name: kibana-service
 labels:
   app: kibana-service
spec:
 type: ClusterIP
 selector:
   app: kibana
 ports:
 - name: kibana
   protocol: TCP
   port: 5601
   targetPort: 5601
