apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: kibana
 labels:
  app: kibana
spec:
 replicas: 1
 selector:
  matchLabels:
   app: kibana
 template:
   metadata:
    labels:
     app: kibana
   spec:
    containers:
    - name: kibana
      image: kibana:8.14.3
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 5601
        name: kibana
      env:
        - name: ELASTIC_CONTAINER
          value: "true"
      volumeMounts:
      - mountPath: /usr/share/kibana/config
        name: conf
    volumes:
    - name: conf
      nfs:
        server: 192.168.1.12
        path: "/var/data/ELK_Kibana_Conf"
---
apiVersion: v1
kind: Service
metadata:
 name: kibana-service
 labels:
   app: kibana-service
spec:
 selector:
  app: kibana
 type: NodePort
 ports:
  - port: 5601
    nodePort: 30435
